# Generated by Django 4.1.3 on 2022-12-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
