# Generated by Django 4.1.3 on 2022-12-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0002_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('date', models.DateField()),
                ('fact_qlid_data1', models.IntegerField()),
                ('fact_qlid_data2', models.IntegerField()),
                ('fact_qoil_data1', models.IntegerField()),
                ('fact_qoil_data2', models.IntegerField()),
                ('forecast_qlid_data1', models.IntegerField()),
                ('forecast_qlid_data2', models.IntegerField()),
                ('forecast_qoil_data1', models.IntegerField()),
                ('forecast_qoil_data2', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pars.company')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pars.table')),
            ],
        ),
    ]
