# Generated by Django 4.1.3 on 2022-12-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0003_table_datarow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarow',
            old_name='fact_qlid_data1',
            new_name='fact_qliq_data1',
        ),
        migrations.RenameField(
            model_name='datarow',
            old_name='fact_qlid_data2',
            new_name='fact_qliq_data2',
        ),
        migrations.RenameField(
            model_name='datarow',
            old_name='forecast_qlid_data1',
            new_name='forecast_qliq_data1',
        ),
        migrations.RenameField(
            model_name='datarow',
            old_name='forecast_qlid_data2',
            new_name='forecast_qliq_data2',
        ),
    ]
